use_frameworks!

platform :ios, '8.0'

target 'FCBaseKit_Example' do
  pod 'FCBaseKit', :path => '../'

  target 'FCBaseKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
